name: Player Status Point Config
id: 94
fields:
  - name: ID
    type: Int32
  - name: Name
    type: String
    subtype: Fixed
    length: 64
  - name: Status Points
    type: Array
    length: 200
    fields:
      - name: Value
        type: Int32